baseURL = "https://robertharrison.ca"
languageCode = "en-us"
title = "Robert Harrison"
theme = "hugo-coder"

paginate = 20
canonifyurls = true

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-40538920-1"

[params]
    author = "Robert Harrison"
    info = "iOS Developer"
    description = "San Diego based Software Developer. Owner of RWH Technology, providing mobile app development and consulting services."
    keywords = "blog,developer,personal,ios,swift"
    avatarurl = "images/avatar.png"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = false
    customSCSS = ["scss/style.css"]

# Social links
[[params.social]]
    name = "Email"
    icon = "fa fa-envelope fa-2x"
    weight = 1
    url = "mailto:harrisonrw@gmail.com"
[[params.social]]
    name = "Github"
    icon = "fa fa-2x fa-github"
    weight = 2
    url = "https://github.com/harrisonrw/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-2x fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/robert-harrison-6a457a2b/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-2x fa-twitter"
    weight = 4
    url = "https://twitter.com/robwh99/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url = "/blog/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"
