baseURL = "https://robertharrison.ca"
languageCode = "en-us"
title = "Robert Harrison"
theme = "hugo-coder"

[pagination]
pagerSize = 20

canonifyurls = true

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-40538920-1"

enableEmoji = true

[params]
    author = "Robert Harrison"
    info = "Software Engineer"
    description = "iOS + watchOS + macOS"
    keywords = "blog,app,developer,software,personal,iOS,watchOS,macOS,swift"
    avatarurl = "images/rharrison-500px.jpg"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = false
    customSCSS = ["scss/style.css"]

# Social links
[[params.social]]
    name = "Email"
    icon = "fa fa-envelope fa-2x"
    weight = 1
    url = "mailto:harrisonrw@gmail.com"
[[params.social]]
    name = "Github"
    icon = "fa fa-2x fa-github"
    weight = 2
    url = "https://github.com/harrisonrw/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-2x fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/robert-harrison-6a457a2b/"
[[params.social]]
    name = "BlueSky"
    icon = "fa-brands fa-2x fa-bluesky"
    weight = 4
    url = "https://bsky.app/profile/harrisonrw.bsky.social"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url = "/blog/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"
