baseURL = "http://robertharrison.ca"
languageCode = "en-us"
title = "Robert Harrison"
theme = "hugo-coder"

paginate = 20
canonifyurls = true

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-40538920-1"

[params]
    author = "Robert Harrison"
    info = "iOS Developer"
    description = "San Diego based Software Developer. Specialized in iOS and Swift. Owner of RWH Technology and Mobile Developer at University of San Diego."
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.png"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = false
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Email"
    icon = "fa fa-envelope fa-2x"
    weight = 1
    url = "mailto:harrisonrw@gmail.com"
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 2
    url = "https://github.com/harrisonrw/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/robert-harrison-6a457a2b/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 4
    url = "https://twitter.com/robwh99/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"
